[tool.codex]
model = "gpt-5-codex"
model_reasoning_effort = "high"

# MISSION: Fill documentation gaps identified in /docs/TODO/ analysis
# Create/extend task files to implement missing features while maintaining project consistency
goal = """
Fill all documentation gaps identified in /docs/TODO/ by creating or extending task files in /docs/tasks/.
Ensure all new tasks follow project architecture patterns: data-driven design, testable core systems,
usage-based skill progression, and formula-parameterized mechanics. Maintain consistency with existing
Milestones M1-M6 structure and conventions.
"""

[execution_phases]

# ============================================================================
# PHASE 0: Gap Analysis & Task Structure Review
# ============================================================================
[execution_phases.phase_0_gap_review]
name = "Review Gaps & Existing Task Structure"
priority = "CRITICAL"
estimated_effort = "15-20m"
objectives = [
  "Read all 11 TODO documents in /docs/TODO/ to understand identified gaps",
  "Read existing task files in /docs/tasks/ to understand current structure",
  "Read CONVENTIONS.md, ARCHITECTURE.md, COMBAT_RULES.md for design patterns",
  "Map gaps to potential Milestones",
  "Identify dependencies between gaps",
  "Create master gap-filling plan with priority levels",
]
outputs = ["codex_outputs/phase0_gap_master_plan.md"]
human_approval_required = true

# ============================================================================
# PHASE 1-11: Gap Filling Phases
# See full config for all 11 phases covering:
# - Magic System (Phase 1)
# - Dungeon Biomes (Phase 2)
# - Economy & Vendors (Phase 3)
# - Procedural Itemization (Phase 4)
# - Quest System (Phase 5)
# - Input & Rebinding (Phase 6)
# - Audio System (Phase 7)
# - Tutorial/FTUE (Phase 8)
# - Localization (Phase 9)
# - Documentation (Phase 10)
# - Master Summary (Phase 11)
# ============================================================================

# See C:\Users\duly3\.codex\config.toml for full phase definitions (file moved to project root)
